### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by MikeBinvt** [JamesKindon/CitrixWEMDoc#2]
Hi James,

Trying to run the script I get the following error:
WARNING: GenericProviderException
Out-File : SQL Server PowerShell provider error: Path SQLSERVER:\wemsettings.html does not exist. Please specify a
valid path.
At C:\install\wem\DocumentWEM.ps1:164 char:62
+ ...  $b -body "<H2><br/>$Heading</H2>" | Out-File -append $OutFile -Force
+                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (SQLSERVER:\wemsettings.html:SqlPath) [Out-File], GenericProviderException
    + FullyQualifiedErrorId : PathDoesNotExist,Microsoft.PowerShell.Commands.OutFileCommand

It then leaves me at a "PS SQLSERVER:" prompt.  This happens if I use either windows authentication or the sa logon.  

Also tried it from my workstation and one of the machines running the Wemagent.

Thanks.

**Comment by JamesKindon** [comment]
Hi Mike, 

What's the exact syntax you are using to execute the script? And are you running this elevated?

**Comment by MikeBinvt** [comment]
Hi James,

My apologies I thought I had updated the thread.  I had an older version of
the Framework installed, once I updated that it worked fine.

Thanks,

Mike
